### ISSUE TITLE
Tag subscriptions not working

### ISSUE THREAD

**Issue by Ma-ryan** [myimouto/myimouto#147]
I got a weird issue on my hands. I put up some tag subscriptions on my install and manually ran the job tasks script. My tag subscription updated with the relevant posts as expected and everything seemed to work fine, so I set up a cron job to run it hourly and I left it to do its thing. But then I noticed it stopped updating the subs and a quick glance at ```/job_task``` showed that ```calculate_tag_subscriptions``` was stuck at ```processing``` for some reason. I tried resetting it manually from the database back to pending and ran the script... only to have it get stuck at processing again. Also, no errors were logged anywhere regarding this.

Any idea what could be wrong?

**Comment by Parziphal** [comment]
I just looked at the code and apparently, what's wrong is that any error while processing subscriptions is ignored, so we can't know what's going on.

**Comment by Ma-ryan** [comment]
Sorry for the late reply.

I added your commit, but there doesn't seem to be any relevant logs of the problem anywhere still.

**Comment by Ma-ryan** [comment]
Revisiting this issue, it seems that setting ```enable_asynchronous_tasks``` to ```true``` in the config made it work again... once. It's stuck at processing again and I can't reproduce it anymore. It's weird that no errors are being logged anywhere. Even the terminal output doesn't show any after running the job tasks script. Pretty annoying since I'd really like to get it to work.

How are tag subscriptions supposed to work in MyImouto anyway? Maybe we can trace the problem?

**Comment by gcscaglia** [comment]
We ~~had~~ have the same problem with the external data search, and in theory it should affect any background task that schedule itself again after done. It's a bug in the framework, and there is a [workaround](https://github.com/myimouto/myimouto/issues/98#issuecomment-109446824), although you will need to adapt it to the ``calculate_tag_subscriptions`` task.

Setting ``enable_asynchronous_tasks`` probably restarts all tasks, that's why it worked again but only once.

**Comment by Ma-ryan** [comment]
How do I go about implementing your workaround for my case? Any tips?

**Comment by gcscaglia** [comment]
First off, you will need some understanding of php and programming in general or else it will be a non-starter.
Second, if your site is live rather than local like mine you should take care, as any error you mistakenly insert on the file will put the whole site down for everyone.

The file you need to edit _probably_ is ``/path/to/myimouto/app/models/JobTasks.php``. There are methods for each task, and they all go along the lines of:
* load the task record from ``job_tasks`` table, update its status to ``processing``.
* do the task itself.
* update the task record previously loaded to ``pending``.

Now, you need to change it so that it becomes:
* load the task record from ``job_tasks`` table, update its status to ``processing``.
* do the task itself.
* load the task record from ``job_tasks`` table *again*, update the _newly loaded_ record status to ``pending``.

Good luck.

**Comment by Parziphal** [comment]
61b48d0 should have fixed this.

**Comment by Ma-ryan** [comment]
Really appreciate you fixing bugs again, but this bug isn't really fixed yet. While the job task is no longer getting stuck at processing, the tag subscriptions are still not updating.

**Comment by Parziphal** [comment]
I don't remember how tag subscriptions work. But I create a tag subscription, then I go to my profile, and I see the subscribed posts. Apparently job tasks have nothing to do here. Am I missing something? heh.

**Comment by Ma-ryan** [comment]
It seems to me that tag subscriptions work only the first time they are run. It doesn't update later when new posts are added. I really doubt the process is even running...

**Comment by Parziphal** [comment]
Oooh right, right. The job task has to update the subscriptions with new/deleted posts. Right... lol. Alright I'm gonna check that.
It's absurd and ridiculous to be fixing things reported over a year ago. But better late than never.

**Comment by Parziphal** [comment]
Ok I found the error and I fixed it, but I found something else that's strange.

Tag subscriptions are supposed to be like post searchs, right? You create a sub called "School nekos" and set tags "nekomimi seifuku", so you'll get all posts tagged with both tags. But the code splits the tag search and searches for all posts tagged with "nekomimi" and all posts tagged with "seifuku". I don't think that's how it's supposed to work, is it?

**Comment by Parziphal** [comment]
So the error was that I made a mistake with a flag that prevented tag subs task to be ran after certain time. The flag was set forever, so as you said, the job was ran only once.

After you update your files, you'll have to manually delete the cache file located at `tmp/cache/app/c4/1b/delay-tag-sub-calc`. Just in case, if that doesn't work, delete the whole `tmp/cache` directory.

I also made that delay time configurable as `tag_subscription_delay`, and added the next time the task will run in the tasks's page.

Please confirm this is finally fixed.

**Comment by Ma-ryan** [comment]
I can confirm that it's finally working! Great work.

By the way, tag subscriptions are supposed to work that way. Many users tend to put multiple artist tags into a single sub for example. If they worked like a regular search, nothing would show up lol.

**Comment by Parziphal** [comment]
You're right. It wouldn't make much sense for it to work like a regular search. Now, what if it allowed groups of tags too... oh well.

I'm glad it's working. Thanks for keep replying after 17 months.
