### ISSUE TITLE
No new tags showed up

### ISSUE THREAD

**Issue by davepatt** [myimouto/myimouto#194]
I trying myimouto and i add first 20 pictures with copyright tag AAA and character tag BBB, so far so good. Then i add some new pictures with tags copyright CCC and character DDD , and they not show up in main post screen only on show screen. In tags i have AAA BBB CCC and DDD, can you help me please ? thank you.

Edit: new tags show up but like hour after adding them

**Comment by Parziphal** [comment]
You mean new tags don't show up in the left sidebar in the post-index page? Check this "Popular tags" info [here](https://github.com/myimouto/myimouto/wiki/About-MyImouto#popular-tags). Is this what you mean?

**Comment by davepatt** [comment]
yes , this is it , i configured post_index_tags_limit to like 100000000000 days to never dissapear , but my problem is they dont show up right away when i created post with new tag (old tag show wrong count number) , but after like one hour they magiccaly appeared , when i click on new image new tags show up even higher number count if tag is old

**Comment by Parziphal** [comment]
I've been checking the code because I've forgotten how some parts work, and I've found out that the sidebar effectively updates every hour, so that's normal.

Every hour, the sidebar updates and searches for all popular tags of posts updated within `post_index_tags_limit` time. It's not updated automatically or every time you upload something. I can think a couple of reasons it is like that: it's the easiest and a very logical way to manage that feature, and saves system resources.

**Comment by davepatt** [comment]
Ok , thank you i adapt myself to this hour update. :)
