### ISSUE TITLE
Blacklisted images

### ISSUE THREAD

**Issue by Yushe** [myimouto/myimouto#201]
Is it possible to have blacklisted images show up in the posts list as the "blacklisted-preview.png" image?

**Comment by Parziphal** [comment]
Everything is possible... but you will have to code it. Currently it is not possible.

If a user blacklists something it's because they don't want to know about it. Why show the blacklisted preview? The blacklisted-posts info on the sidebar should be enough.

**Comment by Yushe** [comment]
What I'm talking about is if users have posts rated e or q blacklisted the posts will show up as the "blacklisted-preview.png" image on the /post page just like they do on the /comment page. Would it be easy to do?

**Comment by Parziphal** [comment]
Yes, I understood your question correctly. In order to do that, you would have to edit some Javascript to prevent getting the blacklisted hidden; instead, the script will have to change the posts preview for the "blacklisted preview", as this can be done on client side too. Then I think you'd like to change JS again to implement a way the user can show the actual preview.

For this I think you'll have to edit the file `lib/assets/javascripts/moe-legacy/post.js`, somewhere around line `496` I believe...

I think you should just appreciate the "Hidden Posts" widget on the left sidebar, where you can see how many posts are blacklisted, show/hide them, add more blacklists... isn't that good enough?

**Comment by Parziphal** [comment]
Or do you mean that you just want the previews to show the "blacklisted preview" image, so when the user unhides the blacklisted posts, they will see that preview? (although that which wouldn't make much sense...)

**Comment by Yushe** [comment]
I just feel like some people wouldn't know the Hidden Posts text is there.

**Comment by Parziphal** [comment]
Well, people has to learn to use the website... You can create a forum post "How to use this site" and create a link to it in the topbar notice, or set remove the default blacklisted tags in your config so nothing is hidden by default, and whenever users feel like hidding something, they will ask and somehow find out.
