### ISSUE TITLE
Complete Rewrite

### ISSUE THREAD

**Issue by rmrhz** [myimouto/myimouto#79]
Hello everyone,

As you may well know that in order to keep the project moving forward I would like to suggest a complete rewrite for myimouto. The rewrite will be compliant to PSR and will have *unit testing* and *continuous integration*. As far as using a framework it may be a good start if we use components of Laravel's `Illuminate` to replace Rails PHP in general. Or we can use Laravel to achieve all of the application's needs.

I know this may be fan boying but the project needs constant community contributions as well as following to community standards.

**Comment by SparoHawk** [comment]
@Parziphal I liked Angular JS 1.2. I don't like Angular JS too much atm. TypeScript isn't for me. Right now I am working with VueJS 1.0 and soon with VueJS 2.0. Angular 1.2 was more robust than VueJS, but with the complete re-write it lost all of that since everything else has to be re-written. As it stands I think VueJS will get a strong hold in the SPA scene.

**Comment by Parziphal** [comment]
Yeah, there are as many frameworks as developers out there. Lately I've been using AngularJS, because I didn't know about other frameworks like VueJS and React. I was thinking of writing a new, backwards-incompatible system using latest PHP, MongoDB, Laravel, and AngularJS (Ng because that's what I know right now).

But the thing is that I finally decided not to rewrite the system, as it is a titanic work and I simply don't have the time to do it. So I've fixed errors reported long ago, to make the system as _stable_ as possible, and leave it there.

**Comment by SparoHawk** [comment]
VueJS is very easy to get into, as it works with bindings very much like Ng does. Check it out if you can. Not that Ng is bad. Just a matter of personal choice (I don't quite like TypeScript).

**Comment by rmrhz** [comment]
Hi guys, I would like to apologize for not giving updates at all. There are a lot of causes back then which I am unable to deliver but I do believe it's not worth to dabble anymore with the past. If someone already started in a rewrite, I would happily contribute to the project.
