### ISSUE TITLE
job_tasks fail

### ISSUE THREAD

**Issue by Doofcake** [myimouto/myimouto#98]
Another php error, this time whenever I try to run the job_tasks
Here's what it tells me

```
*** PDOException in PDO#__construct ***
SQLSTATE[HY000] [1049] Unknown database 'myimouto_dev'
#0 G:\myimouto\vendor\railsphp\railsphp\lib\Rails\ActiveRecord\Conne
ction.php(268): PDO->__construct('mysql:host=127....', 'root', NULL, Array)
#1 G:\myimouto\vendor\railsphp\railsphp\lib\Rails\ActiveRecord\Conne
ction.php(30): Rails\ActiveRecord\Connection->create_connection(Array)
#2 G:\myimouto\vendor\railsphp\railsphp\lib\Rails\ActiveRecord\Activ
eRecord.php(65): Rails\ActiveRecord\Connection->__construct(Array, 'development'
)
#3 G:\myimouto\vendor\railsphp\railsphp\lib\Rails\ActiveRecord\Activ
eRecord.php(51): Rails\ActiveRecord\ActiveRecord::create_connection('development
')
#4 G:\myimouto\vendor\railsphp\railsphp\lib\Rails\ActiveRecord\Activ
eRecord.php(80): Rails\ActiveRecord\ActiveRecord::setConnection('development')
#5 G:\myimouto\vendor\railsphp\railsphp\lib\Rails\Application\Base.p
hp(276): Rails\ActiveRecord\ActiveRecord::set_environment_connection('developmen
t')
#6 G:\myimouto\vendor\railsphp\railsphp\lib\Rails\Application\Base.p
hp(106): Rails\Application\Base->_load_active_record()
#7 G:\myimouto\vendor\railsphp\railsphp\lib\Rails\Application\Base.p
hp(50): Rails\Application\Base->boot()
#8 G:\myimouto\config\boot.php(29): Rails\Application\Base::initiali
ze()
#9 G:\myimouto\script\daemons\job_task_processor.php(3): require('G:
\\...')
#10 {main}
Error context:
```

Basically, it gets an inexistent database name, myimouto_dev (I have the database named simply "myimouto") from somewhere, but I couldn't figure out where. Help would be appreciated. :)

**Comment by gcscaglia** [comment]
I've been struggling with this issue myself, and I think I've pinpointed the root issue, although I still can't solve it. It seems to be an issue with internal value caching at the ActiveRecord framework, `updateAttribute` method; I've guessed that while debugging and watching the mysql log, and messing with the status property values; Any calls setting a value to whatever the value was when the record was fetched is silently ignored.

I've workaround the issue by calling `updateAtrribute` on a newly fetched record. Since this is a dirty hack and doesn't address the root issue, I'm not sending a pull request. Instead, there is a patch bellow in case anyone want's it.

```
diff --git a/app/models/JobTask.php b/app/models/JobTask.php
index fce0814..e1b0198 100755
--- a/app/models/JobTask.php
+++ b/app/models/JobTask.php
@@ -113,8 +113,9 @@ class JobTask extends Rails\ActiveRecord\Base

             if ($count == 0)
                 $this->updateAttribute('status', "finished");
-            else
-                $this->updateAttributes(array('status' => "pending", 'repeat_count' => $count));
+            else {
+                self::where('id = ?', $this->id)->take()[0]->updateAttributes(array('status' => "pending", 'repeat_count' => $count));
+            }
         } catch (Exception $x) {
             $text  = "";
             $text .= "Error executing job: " . $this->task_type . "\n";
@@ -281,4 +282,4 @@ class JobTask extends Rails\ActiveRecord\Base
         $data = array_merge((array)$this->data, $data);
         $this->updateAttributes(array('data' => $data));
     }
-}
\ No newline at end of file
+}
```

**Comment by Parziphal** [comment]
Oh, how I long rewriting this system from scratch...
Is any portable clone device out in the market yet?

**Comment by gcscaglia** [comment]
lol, not that i know of :) Tell me if you find one.

Also, another thing about the `SQLSTATE 23000 Duplicated entry`, I was getting the same problem with another tag, `yuusha ni narenakatta ore wa shibushibu shuushoku o ketsui shimashita.` and figured it out as well.

It turns out that tags names are limited to 64 characters at mysql level and so tags bigger than that get truncated to fit. This particular show was tagged differently between yande.re and danbooru, swapping   `...shuushoku o ketsui...` for `...shuushoku wo ketsui...`. But since the tags where truncated they both became equals and voila. Damn this new trend of naming shows with whole paragraphs.

Solution: Simply run `ALTER TABLE tags MODIFY name varchar(255) NOT NULL UNIQUE;` at mysql console and restart the job. In my case, 255 was the limit mysql accepted due to using utf8 encoding and the unique constraint.

**Comment by jewyti** [comment]
Would it be better if the tag is in text but I fear it would consume too much resource
